/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tr.gov.turkiye.esignuidesk.view.pane;

import java.util.ArrayList;
import javax.swing.JComboBox;
import tr.gov.turkiye.esign.statics.Modules;
import tr.gov.turkiye.esignuidesk.annotation.FocusOwner;
import tr.gov.turkiye.esignuidesk.config.Config;
import tr.gov.turkiye.esignuidesk.controller.LogicManager;
import tr.gov.turkiye.esignuidesk.data.UserData;
import tr.gov.turkiye.esignuidesk.props.ScreenProperties;

/**
 *
 * Screen 1
 * 
 * @author iakpolat
 */
public class CardSelectScreen extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     */
    public CardSelectScreen() {
        initComponents();
        
        setBounds(Config.DEF_PANEL_STARTING_X, Config.DEF_PANEL_STARTING_Y, Config.DEF_PANEL_WIDTH, Config.DEF_PANEL_HEIGHT);
        
        /**
         * Init card types.
         */
        ArrayList<String> modules = Modules.getModuleIdentifiers();
        cardTypes.setModel(new javax.swing.DefaultComboBoxModel(modules.toArray()));
    }

    @FocusOwner
    public JComboBox getCardTypes() {
        return cardTypes;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cardTypes = new javax.swing.JComboBox();
        cardLabel = new javax.swing.JLabel();
        CardSelectApproveBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        ArrayList<String> modules = Modules.getModuleIdentifiers();
        cardTypes.setPreferredSize(null);
        cardTypes.setSize(new java.awt.Dimension(340, 27));
        jPanel1.add(cardTypes);
        cardTypes.setBounds(73, 6, 340, 27);

        cardLabel.setText(ScreenProperties.getValue("card_type")+":");
        jPanel1.add(cardLabel);
        cardLabel.setBounds(6, 10, 84, 16);

        add(jPanel1);
        jPanel1.setBounds(55, 70, 420, 40);

        CardSelectApproveBtn.setText(ScreenProperties.getValue("continue"));
        CardSelectApproveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardSelectApproveBtnActionPerformed(evt);
            }
        });
        add(CardSelectApproveBtn);
        CardSelectApproveBtn.setBounds(200, 140, 128, 29);
    }// </editor-fold>//GEN-END:initComponents

    private void CardSelectApproveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardSelectApproveBtnActionPerformed
        UserData.slcCardType = (String)cardTypes.getSelectedItem();
        LogicManager.done(Config.CARD_SELECT_SCREEN_ID);
    }//GEN-LAST:event_CardSelectApproveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CardSelectApproveBtn;
    private javax.swing.JLabel cardLabel;
    private javax.swing.JComboBox cardTypes;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
